In [ ]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split

np.random.seed(0)

# исходные параметры распределений классов
r1 = 0.3
D1 = 3.0
mean1 = [2, -2]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 5.0
mean2 = [-3, -1]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

# моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V1, N).T
x2 = np.random.multivariate_normal(mean2, V2, N).T

data_x = np.hstack([x1, x2]).T
data_y = np.hstack([np.ones(N) * -1, np.ones(N)])

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, random_state=123,test_size=0.4, shuffle=True)

# здесь продолжайте программу
clf = svm.SVC(kernel='linear')    # SVM с линейным ядром
clf.fit(x_train, y_train)

w = np.hstack((clf.intercept_[0], clf.coef_[0]))

predict = clf.predict(x_test)
acc = np.mean(predict == y_test)

print(acc, predict, w)

0.935 [ 1.  1. -1.  1.  1.  1. -1.  1. -1.  1.  1.  1. -1. -1. -1. -1. -1. -1.
  1. -1.  1. -1. -1. -1.  1. -1.  1.  1.  1. -1.  1.  1.  1.  1. -1. -1.
 -1. -1. -1.  1.  1.  1.  1. -1.  1.  1.  1. -1. -1. -1.  1. -1.  1. -1.
 -1. -1. -1. -1.  1. -1. -1. -1. -1.  1.  1.  1. -1. -1.  1.  1.  1.  1.
  1. -1.  1. -1.  1.  1.  1.  1.  1.  1.  1. -1.  1.  1. -1. -1. -1. -1.
 -1. -1.  1.  1. -1. -1.  1. -1.  1.  1. -1. -1.  1.  1.  1. -1.  1.  1.
  1.  1. -1. -1. -1. -1. -1. -1.  1. -1.  1. -1.  1. -1. -1. -1.  1.  1.
 -1.  1. -1. -1.  1. -1. -1. -1. -1.  1. -1. -1.  1.  1. -1. -1.  1. -1.
 -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.
  1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1.  1.  1.  1. -1. -1. -1.
  1.  1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -1. -1. -1.  1. -1. -1. -1.
  1. -1.  1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1. -1.  1.  1. -1. -1.
 -1.  1. -1. -1. -1.  1. -1. -1. -1.  1. -1.  1.  1.  1. -1. -1. -1.  1.
  1.  1. -1.  1.  1. -1.  1.  1. -1.  1.  1. 

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split


def loss(w, x, y):
    # здесь реализация экспоненциальной функции потерь
    M = np.dot(x, w) * y
    return np.exp(-M)

def df(w, x, y):
    # здесь реализация производной функции потерь по вектору w
    M = np.dot(x, w) * y
    return -np.exp(-M) * x.T * y

np.random.seed(0)

# исходные параметры распределений двух классов
r1 = 0.4
D1 = 2.0
mean1 = [1, -2]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 3.0
mean2 = [2, 3]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

# моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V1, N).T
x2 = np.random.multivariate_normal(mean2, V2, N).T

data_x = np.array([[1, x[0], x[1]] for x in np.hstack([x1, x2]).T])
data_y = np.hstack([np.ones(N) * -1, np.ones(N)])

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, random_state=123,test_size=0.3, shuffle=True)

n_train = len(x_train)  # размер обучающей выборки
w = [0.0, 0.0, 0.0]  # начальные весовые коэффициенты
nt = np.array([0.5, 0.01, 0.01])  # шаг обучения для каждого параметра w0, w1, w2
lm = 0.01  # значение параметра лямбда для вычисления скользящего экспоненциального среднего
N = 500  # число итераций алгоритма SGD
batch_size = 10 # размер мини-батча (величина K = 10)

# здесь продолжайте программу
for _ in range(N):
    k = np.random.randint(0, n_train - batch_size - 1)
    batch = range(k, k + batch_size)
    x_, y_ = x_train[batch], y_train[batch]
    # e = np.mean(loss(w, x_, y_))

    w = w - nt * np.mean(df(w, x_, y_), axis=1)

mrgs = np.sort(np.dot(x_test, w) * y_test)
acc = np.mean(y_test == np.sign(np.dot(x_test, w)))

print(w, mrgs, acc)

[-0.29321218 -0.28605492  1.14218196] [-3.55299766 -1.80257017 -1.46606546 -1.22395902 -1.22152293 -1.1022169
 -1.07395964 -1.02294948 -0.93066453 -0.87060156 -0.63600713 -0.61794943
 -0.55220759 -0.53622761 -0.52492229 -0.52121446 -0.50084156 -0.48835174
 -0.39344097 -0.31931775 -0.30117329 -0.29426115 -0.08728085 -0.04671668
 -0.03154952 -0.01661359 -0.01564917  0.02104521  0.04310211  0.07494689
  0.09321219  0.13517936  0.14813161  0.15393699  0.30143096  0.30720444
  0.33471308  0.33476595  0.34240689  0.3769734   0.38777804  0.40741748
  0.4164529   0.44195698  0.44626687  0.45218705  0.49452606  0.5115335
  0.52711974  0.53356077  0.55079096  0.55371028  0.56882659  0.57182642
  0.58487376  0.65198048  0.65649352  0.66184167  0.67319912  0.67981044
  0.68809847  0.68925688  0.69336498  0.70482563  0.71378614  0.71495011
  0.72094735  0.72355441  0.74098574  0.75832215  0.76907527  0.76916811
  0.8067229   0.80685637  0.82323524  0.84685868  0.85237442  0.85371566
  0.88455512  0

In [ ]:
import numpy as np

# логарифмическая функция потерь
def loss(w, x, y):
    M = np.dot(x, y) * y
    return np.log2(1 + np.exp(-M))

# производная логарифмической функции потерь по вектору w
def df(w, x, y):
    M = np.dot(x, w) * y
    return -(np.exp(-M) * x.T * y) / ((1 + np.exp(-M)) * np.log(2))

a = lambda w, x: np.sign(x @ w)


data_x = [(5.8, 1.2), (5.6, 1.5), (6.5, 1.5), (6.1, 1.3), (6.4, 1.3), (7.7, 2.0), (6.0, 1.8), (5.6, 1.3), (6.0, 1.6), (5.8, 1.9), (5.7, 2.0), (6.3, 1.5), (6.2, 1.8), (7.7, 2.3), (5.8, 1.2), (6.3, 1.8), (6.0, 1.0), (6.2, 1.3), (5.7, 1.3), (6.3, 1.9), (6.7, 2.5), (5.5, 1.2), (4.9, 1.0), (6.1, 1.4), (6.0, 1.6), (7.2, 2.5), (7.3, 1.8), (6.6, 1.4), (5.6, 2.0), (5.5, 1.0), (6.4, 2.2), (5.6, 1.3), (6.6, 1.3), (6.9, 2.1), (6.8, 2.1), (5.7, 1.3), (7.0, 1.4), (6.1, 1.4), (6.1, 1.8), (6.7, 1.7), (6.0, 1.5), (6.5, 1.8), (6.4, 1.5), (6.9, 1.5), (5.6, 1.3), (6.7, 1.4), (5.8, 1.9), (6.3, 1.3), (6.7, 2.1), (6.2, 2.3), (6.3, 2.4), (6.7, 1.8), (6.4, 2.3), (6.2, 1.5), (6.1, 1.4), (7.1, 2.1), (5.7, 1.0), (6.8, 1.4), (6.8, 2.3), (5.1, 1.1), (4.9, 1.7), (5.9, 1.8), (7.4, 1.9), (6.5, 2.0), (6.7, 1.5), (6.5, 2.0), (5.8, 1.0), (6.4, 2.1), (7.6, 2.1), (5.8, 2.4), (7.7, 2.2), (6.3, 1.5), (5.0, 1.0), (6.3, 1.6), (7.7, 2.3), (6.4, 1.9), (6.5, 2.2), (5.7, 1.2), (6.9, 2.3), (5.7, 1.3), (6.1, 1.2), (5.4, 1.5), (5.2, 1.4), (6.7, 2.3), (7.9, 2.0), (5.6, 1.1), (7.2, 1.8), (5.5, 1.3), (7.2, 1.6), (6.3, 2.5), (6.3, 1.8), (6.7, 2.4), (5.0, 1.0), (6.4, 1.8), (6.9, 2.3), (5.5, 1.3), (5.5, 1.1), (5.9, 1.5), (6.0, 1.5), (5.9, 1.8)]
data_y = [-1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1]

x_train = np.array([[1, x[0], x[1]] for x in data_x])
y_train = np.array(data_y)

n_train = len(x_train)  # размер обучающей выборки
w = [0.0, 0.0, 0.0]  # начальные весовые коэффициенты
nt = np.array([0.5, 0.01, 0.01])  # шаг обучения для каждого параметра w0, w1, w2
lm = 0.01  # значение параметра лямбда для вычисления скользящего экспоненциального среднего
N = 500  # число итераций алгоритма SGD

np.random.seed(0) # генерация одинаковых последовательностей псевдослучайных чисел

# здесь продолжайте программу
for _ in range(N):
    k = np.random.randint(0, n_train-1) # n_train - размер выборки (массива x_train)
    x_, y_ = x_train[k], y_train[k]
    w = w - nt * df(w, x_, y_)

TP = np.sum((a(w, x_train) == 1) & (a(w, x_train) == y_train))
TP_FP = np.sum(a(w, x_train) == 1)
TP_FN = np.sum(y_train == 1)

# TP = ((predict == 1) & (y_train == 1)).sum()
# TN = ((predict == -1) & (y_train == -1)).sum()
# FP = ((predict == 1) & (y_train == -1)).sum()
# FN = ((predict == -1) & (y_train == 1)).sum()

# precision = TP / (TP + FP)
# recall = TP / (TP + FN)

precision = TP / TP_FP
recall = TP / TP_FN

print(w, precision, recall)

[-4.18645163  0.37578382  0.98668124] 0.9722222222222222 0.7


In [ ]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split

np.random.seed(0)

# исходные параметры распределений классов
r1 = 0.2
D1 = 3.0
mean1 = [2, -2]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 2.0
mean2 = [-1, -1]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

a = lambda w, x: np.sign(x @ w)

# моделирование обучающей выборки
N1 = 2500
N2 = 1500
x1 = np.random.multivariate_normal(mean1, V1, N1).T
x2 = np.random.multivariate_normal(mean2, V2, N2).T

data_x = np.hstack([x1, x2]).T
data_y = np.hstack([np.ones(N1) * -1, np.ones(N2)])

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, random_state=123,test_size=0.4, shuffle=True)

# здесь продолжайте программу
clf = svm.SVC(kernel="linear")
clf.fit(x_train, y_train)

w = np.hstack((clf.intercept_[0], clf.coef_[0]))

x_test_r = [[1, *x_] for x_ in x_test]
TP = np.sum((a(w, x_test_r) == 1) & (a(w, x_test_r) == y_test))
TN = np.sum((a(w, x_test_r) == -1) & (a(w, x_test_r) == y_test))
FP = np.sum((a(w, x_test_r) == 1) & (a(w, x_test_r) != y_test))
FN = np.sum((a(w, x_test_r) == -1) & (a(w, x_test_r) != y_test))

precision = TP / (TP + FP)
recall = TP / (TP + FN)

F = (2 * precision * recall) / (precision + recall)
betta = 0.5
Fb = ((1 + betta**2) * precision * recall) / (betta**2 * precision + recall)

print(w, TP, TN, FP, FN, precision, recall)
print(F, Fb)

[ 0.98767546 -1.11039704  0.62827614] 520 877 121 82 0.8112324492979719 0.8637873754152824
0.8366854384553499 0.8212255211623498


In [ ]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split

np.random.seed(0)

# исходные параметры распределений классов
r1 = 0.2
D1 = 3.0
mean1 = [2, -2]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 2.0
mean2 = [-1, -1]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

# моделирование обучающей выборки
N1 = 1000
N2 = 1000
x1 = np.random.multivariate_normal(mean1, V1, N1).T
x2 = np.random.multivariate_normal(mean2, V2, N2).T

data_x = np.hstack([x1, x2]).T
data_y = np.hstack([np.ones(N1) * -1, np.ones(N2)])

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, random_state=123,test_size=0.5, shuffle=True)

# здесь продолжайте программу
clf = svm.SVC(kernel="linear")
clf.fit(x_train, y_train)

w = np.hstack((clf.intercept_[0], clf.coef_[0]))

t = 2
a = lambda w, x: np.sign([[1, *x_] for x_ in x] @ w - t)

TP = np.sum((a(w, x_test) == 1) & (a(w, x_test) == y_test))
TN = np.sum((a(w, x_test) == -1) & (a(w, x_test) == y_test))
FP = np.sum((a(w, x_test) == 1) & (a(w, x_test) != y_test))
FN = np.sum((a(w, x_test) == -1) & (a(w, x_test) != y_test))

FPR = FP / (FP + TN)
TPR = TP / (TP + FN)

print(w, TP, TN, FP, FN)
print(FPR, TPR)

[ 1.44983814 -1.13814782  0.69057845] 226 494 12 268
0.023715415019762844 0.4574898785425101


In [ ]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split

np.random.seed(0)

# исходные параметры распределений классов
r1 = -0.2
D1 = 3.0
mean1 = [1, -5]
V1 = [[D1, D1 * r1], [D1 * r1, D1]]

r2 = 0.5
D2 = 2.0
mean2 = [-1, -2]
V2 = [[D2, D2 * r2], [D2 * r2, D2]]

# моделирование обучающей выборки
N1 = 1000
N2 = 1000
x1 = np.random.multivariate_normal(mean1, V1, N1).T
x2 = np.random.multivariate_normal(mean2, V2, N2).T

data_x = np.hstack([x1, x2]).T
data_y = np.hstack([np.ones(N1) * -1, np.ones(N2)])

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, random_state=123,test_size=0.5, shuffle=True)

# здесь продолжайте программу
clf = svm.SVC(kernel="linear")
clf.fit(x_train, y_train)

w = np.hstack((clf.intercept_[0], clf.coef_[0]))

range_t = np.arange(5.7, -7.8, -0.1)
a = lambda w, x, t: np.sign([[1, *x_] for x_ in x] @ w - t)

FPR = []
TPR = []

for t in range_t:
  TP = np.sum((a(w, x_test, t) == 1) & (a(w, x_test, t) == y_test))
  TN = np.sum((a(w, x_test, t) == -1) & (a(w, x_test, t) == y_test))
  FP = np.sum((a(w, x_test, t) == 1) & (a(w, x_test, t) != y_test))
  FN = np.sum((a(w, x_test, t) == -1) & (a(w, x_test, t) != y_test))

  FPR.append(FP / (FP + TN))
  TPR.append(TP / (TP + FN))

print(w, TP, TN, FP, FN)
print(FPR, TPR)

[ 2.89510333 -0.68396208  0.88756218] 494 1 505 0
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001976284584980237, 0.001976284584980237, 0.003952569169960474, 0.005928853754940711, 0.005928853754940711, 0.007905138339920948, 0.007905138339920948, 0.007905138339920948, 0.009881422924901186, 0.009881422924901186, 0.009881422924901186, 0.01383399209486166, 0.015810276679841896, 0.017786561264822136, 0.021739130434782608, 0.025691699604743084, 0.02766798418972332, 0.03359683794466403, 0.037549407114624504, 0.041501976284584984, 0.04743083003952569, 0.04940711462450593, 0.04940711462450593, 0.0533596837944664, 0.06126482213438735, 0.06719367588932806, 0.0691699604743083, 0.07312252964426877, 0.07905138339920949, 0.08695652173913043, 0.09683794466403162, 0.1067193675889328, 0.11462450592885376, 0.12648221343873517, 0.13636363636363635, 0.1482213438735178, 0.16403162055335968, 0.17984189723320157, 0.1897233201581027