In [ ]:
import numpy as np

np.random.seed(0)

# исходные параметры для формирования образов обучающей выборки
r = 0.7
D = 3.0
mean = [3, 7, -2, 4, 6]
n_feature = 5
V = [[D * r ** abs(i-j) for j in range(n_feature)] for i in range(n_feature)]

# моделирование обучающей выборки
N = 1000
X = np.random.multivariate_normal(mean, V, N).T

# здесь продолжайте программу
F = X @ X.T / N
L, W = np.linalg.eig(F)

print(F, L, W)

[[ 12.35895175  23.9291307   -4.43167014  13.77789234  19.48512592]
 [ 23.9291307   53.24816975 -11.4204177   30.45109577  43.80533989]
 [ -4.43167014 -11.4204177    6.59979547  -5.63334686  -9.96274324]
 [ 13.77789234  30.45109577  -5.63334686  19.63688687  26.60382879]
 [ 19.48512592  43.80533989  -9.96274324  26.60382879  39.18836716]] [121.97087918   4.65931132   2.65089954   1.01874301   0.73233795] [[-0.29681658 -0.22479594  0.55492499 -0.73859524 -0.08889331]
 [-0.65500922  0.00277807  0.45638698  0.59194603  0.11075205]
 [ 0.14340159 -0.92536417 -0.05386004  0.14567391  0.31466704]
 [-0.38793169 -0.2938037  -0.40838809  0.03135558 -0.77163747]
 [-0.55839755  0.08270195 -0.56043504 -0.2861344   0.53422115]]


In [ ]:
import numpy as np

data_x = [(1.3, 5.5), (1.5, 4.9), (4.9, 6.3), (1.5, 5.2), (3.5, 5.7), (1.4, 4.6), (4.8, 5.9), (4.5, 5.7), (3.7, 5.5), (1.5, 5.3), (4.6, 6.1), (1.6, 4.8), (1.5, 5.0), (4.0, 5.5), (1.3, 4.7), (1.4, 5.0), (1.7, 5.1), (1.5, 5.2), (3.9, 5.2), (1.5, 4.6), (4.1, 5.8), (1.9, 5.1), (4.0, 5.5), (4.6, 6.6), (4.5, 6.4), (4.5, 6.0), (4.7, 6.1), (1.3, 4.5), (5.1, 6.0), (4.4, 6.6), (4.0, 6.1), (4.5, 6.2), (3.8, 5.5), (1.5, 5.4), (4.9, 6.9), (3.0, 5.1), (4.5, 5.6), (1.4, 4.9), (4.0, 5.8), (5.0, 6.7), (4.4, 5.5), (3.9, 5.6), (1.4, 4.6), (3.3, 4.9), (3.9, 5.8), (4.2, 5.7), (4.4, 6.3), (1.4, 5.1), (1.6, 5.0), (1.5, 5.1), (4.7, 6.3), (3.6, 5.6), (4.4, 6.7), (1.7, 5.4), (1.3, 4.4), (4.1, 5.6), (1.0, 4.6), (4.3, 6.2), (1.4, 4.4), (4.5, 6.0), (4.7, 6.7), (3.3, 5.0), (1.5, 4.9), (3.5, 5.0), (1.6, 4.7), (1.4, 4.9), (1.4, 4.8), (1.3, 5.0), (4.6, 6.5), (4.0, 6.0), (4.7, 6.1), (1.6, 5.0), (1.4, 5.2), (4.7, 7.0), (1.1, 4.3), (1.6, 5.1), (4.3, 6.4), (1.2, 5.8), (1.9, 4.8), (1.4, 4.8), (1.5, 5.1), (4.8, 6.8), (4.1, 5.7), (1.7, 5.7), (1.6, 5.0), (4.2, 5.7), (1.6, 4.8), (1.2, 5.0), (1.3, 4.4), (1.7, 5.4), (4.5, 5.4), (4.2, 5.6), (1.5, 5.4), (1.4, 5.5), (1.4, 5.1), (1.5, 5.1), (4.2, 5.9), (1.5, 5.7), (1.4, 5.0), (1.3, 5.4)]
X = np.array([[x[0], x[1], 0.8 * x[0], 1.5 * x[0] - 0.8 * x[1]] for x in data_x])

# здесь продолжайте программу
F = 1 / len(data_x) * X.T @ X
L, W = np.linalg.eig(F)
L = np.sort(L)[::-1]

print(L)

[4.57419306e+01 4.58596442e+00 9.94386201e-15 2.77384669e-15]


In [ ]:
import numpy as np

data_x = [(1.3, 5.5), (1.5, 4.9), (4.9, 6.3), (1.5, 5.2), (3.5, 5.7), (1.4, 4.6), (4.8, 5.9), (4.5, 5.7), (3.7, 5.5), (1.5, 5.3), (4.6, 6.1), (1.6, 4.8), (1.5, 5.0), (4.0, 5.5), (1.3, 4.7), (1.4, 5.0), (1.7, 5.1), (1.5, 5.2), (3.9, 5.2), (1.5, 4.6), (4.1, 5.8), (1.9, 5.1), (4.0, 5.5), (4.6, 6.6), (4.5, 6.4), (4.5, 6.0), (4.7, 6.1), (1.3, 4.5), (5.1, 6.0), (4.4, 6.6), (4.0, 6.1), (4.5, 6.2), (3.8, 5.5), (1.5, 5.4), (4.9, 6.9), (3.0, 5.1), (4.5, 5.6), (1.4, 4.9), (4.0, 5.8), (5.0, 6.7), (4.4, 5.5), (3.9, 5.6), (1.4, 4.6), (3.3, 4.9), (3.9, 5.8), (4.2, 5.7), (4.4, 6.3), (1.4, 5.1), (1.6, 5.0), (1.5, 5.1), (4.7, 6.3), (3.6, 5.6), (4.4, 6.7), (1.7, 5.4), (1.3, 4.4), (4.1, 5.6), (1.0, 4.6), (4.3, 6.2), (1.4, 4.4), (4.5, 6.0), (4.7, 6.7), (3.3, 5.0), (1.5, 4.9), (3.5, 5.0), (1.6, 4.7), (1.4, 4.9), (1.4, 4.8), (1.3, 5.0), (4.6, 6.5), (4.0, 6.0), (4.7, 6.1), (1.6, 5.0), (1.4, 5.2), (4.7, 7.0), (1.1, 4.3), (1.6, 5.1), (4.3, 6.4), (1.2, 5.8), (1.9, 4.8), (1.4, 4.8), (1.5, 5.1), (4.8, 6.8), (4.1, 5.7), (1.7, 5.7), (1.6, 5.0), (4.2, 5.7), (1.6, 4.8), (1.2, 5.0), (1.3, 4.4), (1.7, 5.4), (4.5, 5.4), (4.2, 5.6), (1.5, 5.4), (1.4, 5.5), (1.4, 5.1), (1.5, 5.1), (4.2, 5.9), (1.5, 5.7), (1.4, 5.0), (1.3, 5.4)]

X = np.array([[x[0], x[1], x[0] * x[1]] for x in data_x]) # матрицу X не менять

# здесь продолжайте программу
F = X.T @ X / X.shape[0]
L, W = np.linalg.eig(F)

# WW = sorted(zip(L, W), key=lambda lx: lx[0], reverse=True)
# WW = np.array([w[1] for w in WW])

WW = W[np.argsort(-L)]

G = np.dot(X, WW.T)

print(G)

[[  5.31544907   2.34205142  -7.02305463]
 [  4.74697866   2.67149716  -7.11419683]
 [  5.63160506  11.928115   -29.02864097]
 [  5.02289989   2.74746471  -7.57310467]
 [  5.29879348   7.7935664  -18.81291074]
 [  4.47538985   2.37861731  -6.23752077]
 [  5.33395916  11.21625237 -26.56345163]
 [  5.20680591  10.25331095 -24.05039057]
 [  5.1159138    8.1186216  -19.13054911]
 [  5.11487364   2.77278723  -7.72607395]
 [  5.51064533  10.92818538 -26.38069659]
 [  4.6497877    2.86837096  -7.39826482]
 [  4.8389524    2.69681968  -7.26716611]
 [  5.09097189   8.84069288 -20.64398592]
 [  4.57258081   2.18174352  -5.95345278]
 [  4.84505441   2.46933933  -6.81085979]
 [  4.91783736   3.18238692  -8.35201707]
 [  5.02289989   2.74746471  -7.57310467]
 [  4.85521696   8.3338098  -18.98691345]
 [  4.47105743   2.5955296   -6.65528899]
 [  5.32407245   9.36342805 -22.35886553]
 [  4.90474857   3.64263165  -9.28389876]
 [  5.09097189   8.84069288 -20.64398592]
 [  5.90194305  11.46431034 -28.63

In [ ]:
import numpy as np


def func(x):
    return 0.5 * x + 0.2 * x ** 2 - 0.05 * x ** 3 + 0.2 * np.sin(4 * x) - 3


coord_x = np.arange(-4.0, 6.0, 0.1)
coord_y = func(coord_x)
K = 10
X = np.array([[xx**i for i in range(K)] for xx in coord_x]) # обучающая выборка для поиска коэффициентов модели
Y = coord_y

X_train = X[::2]  # обучающая выборка (входы)
Y_train = Y[::2]  # обучающая выборка (целевые значения)

# здесь продолжайте программу
F = X_train.T @ X_train / X_train.shape[0]
L, W = np.linalg.eig(F)
W = W[np.argsort(L)]

G = (X @ W.T)[:, :7]
XX_train = G[::2]

w = np.linalg.inv(XX_train.T @ XX_train) @ XX_train.T @ Y_train
predict = G @ w

print(w, predict)

[ 0.00040116 -0.00917001  0.00651972 -0.03638515  0.035082   -0.11518804
  0.1845639 ] [ 7.43539260e-01  1.27412183e+00  1.37610040e+00  1.18001890e+00
  7.90690677e-01  2.90840563e-01 -2.55627767e-01 -8.00712110e-01
 -1.30971405e+00 -1.75893873e+00 -2.13366863e+00 -2.42638932e+00
 -2.63524582e+00 -2.76270978e+00 -2.81443846e+00 -2.79830753e+00
 -2.72360092e+00 -2.60034170e+00 -2.43874914e+00 -2.24880782e+00
 -2.03993578e+00 -1.82073941e+00 -1.59884372e+00 -1.38078745e+00
 -1.17197321e+00 -9.76663737e-01 -7.98015970e-01 -6.38145444e-01
 -4.98214182e-01 -3.78535920e-01 -2.78693126e-01 -1.97660926e-01
 -1.33933591e-01 -8.56498375e-02 -5.07136965e-02 -2.69082273e-02
 -1.19998319e-02 -3.83137114e-03 -4.02716064e-04  6.22360265e-05
 -9.37323496e-04 -2.21761778e-03 -2.93447510e-03 -2.59356886e-03
 -1.04733528e-03  1.52056350e-03  4.62214990e-03  7.50214792e-03
  9.18367984e-03  8.52108260e-03  4.25817765e-03 -4.90975198e-03
 -2.02720766e-02 -4.30388526e-02 -7.42785986e-02 -1.14859614e-01
 -1

In [ ]:
# Сингулярное разложение

In [1]:
import numpy as np

np.random.seed(0)

n_total = 1000 # число образов выборки
n_features = 200 # число признаков

table = np.zeros(shape=(n_total, n_features))

for _ in range(100):
    i, j = np.random.randint(0, n_total), np.random.randint(0, n_features)
    table[i, j] = np.random.randint(1, 10)

# матрицу table не менять

# здесь продолжайте программу
F = table.T @ table / n_total
L, W = np.linalg.eig(F)
WW = W[np.argsort(-L)]
data_x = table @ WW.T[:, :np.sum(L > 0.01)]

print(WW, data_x)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99609929 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
